# ErpIntegration Context Fragment

metadata:
  name: ErpIntegration
  description: ERP Integration bounded context services

services:
  erpreadmodel-readmodelgenerator:
    image: amssolution/erpreadmodel.readmodelgenerator:linux-v3.1.0-pre
    containerName: erpreadmodel-readmodelgenerator
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__ams: ${AMS_DB}
      ConnectionStrings__Transport: ${AMS_DB}
      ConnectionStrings__Persistence: ${AMS_DB}
      ServiceBusTimeToWaitBeforeTriggeringCircuitBreaker: ${SERVICE_BUS_TIME_TO_WAIT_BEFORE_TRIGGERING_CIRCUIT_BREAKER}
      ExitOnCriticalError: ${EXIT_ON_CRITICAL_ERROR}
      Serilog__MinimumLevel: ${LOG_LEVEL}
    networks:
      - ams-project-backend
    restart: unless-stopped

  planning-capacityutilization-api:
    image: amssolution/planning.capacityutilization.api:linux-v3.1.0-pre
    containerName: planning-capacityutilization-api
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ASPNETCORE_HTTP_PORTS: "8080"
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__ams: ${AMS_DB}
      Serilog__MinimumLevel: ${LOG_LEVEL}
    networks:
      - ams-project-backend
    restart: unless-stopped
    healthCheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/hc"]
      interval: 30s
      timeout: 10s
      retries: 3
      startPeriod: 40s

  planning-typecurve-api:
    image: amssolution/planning.typecurve.api:linux-v3.1.0-pre
    containerName: planning-typecurve-api
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ASPNETCORE_HTTP_PORTS: "8080"
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__ams: ${AMS_DB}
      Serilog__MinimumLevel: ${LOG_LEVEL}
    networks:
      - ams-project-backend
    restart: unless-stopped
    healthCheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/hc"]
      interval: 30s
      timeout: 10s
      retries: 3
      startPeriod: 40s

  wage-data-api:
    image: amssolution/wage.wagedata.api:linux-v3.1.0-pre
    containerName: wage-data-api
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ASPNETCORE_HTTP_PORTS: "8080"
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__ams: ${AMS_DB}
      ServiceBusTimeToWaitBeforeTriggeringCircuitBreaker: ${SERVICE_BUS_TIME_TO_WAIT_BEFORE_TRIGGERING_CIRCUIT_BREAKER}
      ExitOnCriticalError: ${EXIT_ON_CRITICAL_ERROR}
      Serilog__MinimumLevel: ${LOG_LEVEL}
    networks:
      - ams-project-backend
    restart: unless-stopped
    healthCheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/hc"]
      interval: 30s
      timeout: 10s
      retries: 3
      startPeriod: 40s


networks:
  ams-project-backend:
    external: true
