# Export Context Fragment

metadata:
  name: Export
  description: Export bounded context services

services:
  export-migrator:
    image: amssolution/export.migrator:linux-v3.1.0-rc
    containerName: export-migrator
    lifecycle: init
    environment:
      DB_SERVER: ${DB_SERVER}
      DB_NAME: ${DB_NAME}
      DB_PARAMS: ${DB_PARAMS}
      DB_ADMIN_USER: ${DB_ADMIN_USER}
      DB_ADMIN_PASSWORD: ${DB_ADMIN_PASSWORD}
      DB_RUNTIME_USER: ${DB_RUNTIME_USER}
      DB_RUNTIME_PASSWORD: ${DB_RUNTIME_PASSWORD}
    networks:
      - ams-project-backend

  export-api:
    image: amssolution/export.api:linux-v3.1.0-rc
    containerName: export-api
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: http://0.0.0.0:8080
      DB_SERVER: ${DB_SERVER}
      DB_NAME: ${DB_NAME}
      DB_PARAMS: ${DB_PARAMS}
      DB_RUNTIME_USER: ${DB_RUNTIME_USER}
      DB_RUNTIME_PASSWORD: ${DB_RUNTIME_PASSWORD}
      ConnectionStrings__cache: ${REDIS_CONNECTION}
      Serilog__MinimumLevel: ${LOG_LEVEL}
    networks:
      - ams-project-backend
      - ams-project-infra
    restart: unless-stopped
    healthCheck:
      type: http
      path: /hc
      port: 8080
      test: ["CMD", "curl", "-f", "http://localhost:8080/hc"]
      interval: 30s
      timeout: 10s
      retries: 3
      startPeriod: 40s

  export-web:
    image: amssolution/export-web:linux-v3.1.0-rc
    containerName: export-web
    environment:
      NODE_ENV: production
      HOSTNAME: "0.0.0.0"
      NEXT_PUBLIC_API_BASE_URL: http://${AMS_PROJECT_EXTERNAL_DNS_NAME_OR_IP}:${BFF_PORT}
      API_BASE_URL: http://web-bff:5000
    networks:
      - ams-project-backend
    restart: unless-stopped
    healthCheck:
      type: http
      path: /export/hc
      port: 3000
      test: ["CMD", "curl", "-f", "http://localhost:3000/export/hc"]
      interval: 30s
      timeout: 10s
      retries: 3
      startPeriod: 40s

  export-readmodelgenerator:
    image: amssolution/export.readmodelgenerator:linux-v3.1.0-rc
    containerName: export-readmodelgenerator
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: http://0.0.0.0:8080
      DB_SERVER: ${DB_SERVER}
      DB_NAME: ${DB_NAME}
      DB_PARAMS: ${DB_PARAMS}
      DB_RUNTIME_USER: ${DB_RUNTIME_USER}
      DB_RUNTIME_PASSWORD: ${DB_RUNTIME_PASSWORD}
      QUEUE_PEEKER_DELAY_MS: "1000"
      Serilog__MinimumLevel: ${LOG_LEVEL}
    networks:
      - ams-project-backend
      - ams-project-infra
    restart: unless-stopped
    healthCheck:
      type: http
      path: /hc
      port: 8080
      test: ["CMD", "curl", "-f", "http://localhost:8080/hc"]
      interval: 30s
      timeout: 10s
      retries: 3
      startPeriod: 40s


networks:
  ams-project-backend:
    external: true
  ams-project-infra:
    external: true
