# Memo Context Fragment

metadata:
  name: Memo
  description: Memo bounded context services

services:
  memo-api:
    image: amssolution/memo.api:linux-v3.1.0-pre
    containerName: memo-api
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ASPNETCORE_HTTP_PORTS: "8080"
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__Transport: ${AMS_DB}
      ConnectionStrings__Persistence: ${AMS_DB}
      Serilog__MinimumLevel: ${LOG_LEVEL}
    networks:
      - ams-project-backend
    restart: unless-stopped
    healthCheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/hc"]
      interval: 30s
      timeout: 10s
      retries: 3
      startPeriod: 40s

  memo-web:
    image: amssolution/memo-web:linux-v3.1.0-pre
    containerName: memo-web
    environment:
      NODE_ENV: ${NODE_ENV}
      NEXT_PUBLIC_API_BASE_URL: http://${AMS_PROJECT_EXTERNAL_DNS_NAME_OR_IP}:${BFF_PORT}
      API_BASE_URL: http://memo-api:8080
    networks:
      - ams-project-backend
    restart: unless-stopped
    healthCheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      startPeriod: 40s


networks:
  ams-project-backend:
    external: true
