# ProductionPlanning Context Fragment

metadata:
  name: ProductionPlanning
  description: Production Planning (Bill of Materials) bounded context services

services:
  bom-api:
    image: amssolution/productionplanning.billofmaterials.webapi:linux-v3.1.0-pre
    containerName: bom-api
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__ams: ${AMS_DB}
      ConnectionStrings__Transport: ${AMS_DB}
      ConnectionStrings__Persistence: ${AMS_DB}
      Serilog__MinimumLevel: ${LOG_LEVEL}
    networks:
      - ams-project-backend
    restart: unless-stopped
    healthCheck:
      type: http
      path: /hc
      port: 8080
      test: ["CMD", "curl", "-f", "http://localhost:8080/hc"]
      interval: 30s
      timeout: 10s
      retries: 3
      startPeriod: 40s

  bom-readmodelgenerator:
    image: amssolution/productionplanning.readmodelgenerator:linux-v3.1.0-pre
    containerName: bom-readmodelgenerator
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__ams: ${AMS_DB}
      ConnectionStrings__Transport: ${AMS_DB}
      ConnectionStrings__Persistence: ${AMS_DB}
      Serilog__MinimumLevel: ${LOG_LEVEL}
    networks:
      - ams-project-backend
    restart: unless-stopped
    healthCheck:
      type: http
      path: /hc
      port: 8080
      test: ["CMD", "curl", "-f", "http://localhost:8080/hc"]
      interval: 30s
      timeout: 10s
      retries: 3
      startPeriod: 40s


  bom-link-client:
    image: amssolution/bom.link.client:linux-v3.1.0-pre
    containerName: bom-link-client
    environment:
      NODE_ENV: ${NODE_ENV}
    networks:
      - ams-project-backend
    restart: unless-stopped
    healthCheck:
      type: http
      path: /bom-link-client/hc
      port: 8080
      test: ["CMD", "curl", "-f", "http://localhost:8080/bom-link-client/hc"]
      interval: 30s
      timeout: 10s
      retries: 3
      startPeriod: 40s

networks:
  ams-project-backend:
    external: true
