# ProductionPlanning Context Fragment

metadata:
  name: ProductionPlanning
  description: Production Planning (Bill of Materials) bounded context services

services:
  productionplanning-migrator:
    image: amssolution/productionplanning.migrator:linux-v3.1.0-rc
    containerName: productionplanning-migrator
    lifecycle: init
    environment:
      DB_SERVER: ${DB_SERVER}
      DB_NAME: ${DB_NAME}
      DB_PARAMS: ${DB_PARAMS}
      DB_ADMIN_USER: ${DB_ADMIN_USER}
      DB_ADMIN_PASSWORD: ${DB_ADMIN_PASSWORD}
      DB_RUNTIME_USER: ${DB_RUNTIME_USER}
      DB_RUNTIME_PASSWORD: ${DB_RUNTIME_PASSWORD}
    networks:
      - ams-project-backend

  bom-api:
    image: amssolution/productionplanning.billofmaterials.webapi:linux-v3.1.0-rc
    containerName: bom-api
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      DB_SERVER: ${DB_SERVER}
      DB_NAME: ${DB_NAME}
      DB_PARAMS: ${DB_PARAMS}
      DB_RUNTIME_USER: ${DB_RUNTIME_USER}
      DB_RUNTIME_PASSWORD: ${DB_RUNTIME_PASSWORD}
      Serilog__MinimumLevel: ${LOG_LEVEL}
    networks:
      - ams-project-backend
    restart: unless-stopped
    healthCheck:
      type: http
      path: /hc
      port: 8080
      test: ["CMD", "curl", "-f", "http://localhost:8080/hc"]
      interval: 30s
      timeout: 10s
      retries: 3
      startPeriod: 40s

  bom-readmodelgenerator:
    image: amssolution/productionplanning.readmodelgenerator:linux-v3.1.0-rc
    containerName: bom-readmodelgenerator
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      DB_SERVER: ${DB_SERVER}
      DB_NAME: ${DB_NAME}
      DB_PARAMS: ${DB_PARAMS}
      DB_RUNTIME_USER: ${DB_RUNTIME_USER}
      DB_RUNTIME_PASSWORD: ${DB_RUNTIME_PASSWORD}
      QUEUE_PEEKER_DELAY_MS: "1000"
      Serilog__MinimumLevel: ${LOG_LEVEL}
    networks:
      - ams-project-backend
    restart: unless-stopped
    healthCheck:
      type: http
      path: /hc
      port: 8080
      test: ["CMD", "curl", "-f", "http://localhost:8080/hc"]
      interval: 30s
      timeout: 10s
      retries: 3
      startPeriod: 40s


  bom-link-client:
    image: amssolution/bom.link.client:linux-v3.1.0-rc
    containerName: bom-link-client
    environment:
      NODE_ENV: ${NODE_ENV}
      HOSTNAME: "0.0.0.0"
    networks:
      - ams-project-backend
    restart: unless-stopped
    healthCheck:
      type: http
      path: /bom-link-client/hc
      port: 3000
      test: ["CMD", "curl", "-f", "http://localhost:3000/bom-link-client/hc"]
      interval: 30s
      timeout: 10s
      retries: 3
      startPeriod: 40s

networks:
  ams-project-backend:
    external: true
