# ProjectImport Context Fragment

metadata:
  name: ProjectImport
  description: Project Import bounded context services

services:
  projectimport-api:
    image: amssolution/projectimport.api:linux-v3.1.0-pre
    containerName: projectimport-api
    ports:
      - "${PROJECT_IMPORT_PORT}:8080"
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ASPNETCORE_HTTP_PORTS: "8080"
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      InternalApi__BaseUrl: http://projectmanagement-api:8080
      InternalApi__AccountingUrl: http://accounting-api:8080
      InternalApi__MemoUrl: http://memo-api:8080
      InternalApi__DiscussionUrl: http://discussions-api:8080
      ConnectionStrings__Transport: ${AMS_DB}
      ConnectionStrings__Persistence: ${AMS_DB}
      Serilog__MinimumLevel: ${LOG_LEVEL}
    networks:
      - ams-project-backend
    restart: unless-stopped


networks:
  ams-project-backend:
    external: true
