# ProjectExporting Context Fragment

metadata:
  name: ProjectExporting
  description: Project Exporting bounded context services

services:
  projectexporting-migrator:
    image: amssolution/projectexporting.migrator:linux-v3.1.0-pre
    containerName: projectexporting-migrator
    lifecycle: init
    environment:
      ConnectionStrings__ProjectExporting: ${AMS_DB}
      ConnectionStrings__Transport: ${AMS_DB}
      ConnectionStrings__Persistence: ${AMS_DB}
      ConnectionStrings__ams: ${AMS_DB}
    networks:
      - ams-project-backend

  projectexporting-readmodelgenerator:
    image: amssolution/projectexporting.readmodelgenerator:linux-v3.1.0-pre
    containerName: projectexporting-readmodelgenerator
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ASPNETCORE_HTTP_PORTS: "8080"
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__ams: ${AMS_DB}
      ConnectionStrings__Transport: ${AMS_DB}
      ConnectionStrings__Persistence: ${AMS_DB}
      ServiceBusTimeToWaitBeforeTriggeringCircuitBreaker: ${SERVICE_BUS_TIME_TO_WAIT_BEFORE_TRIGGERING_CIRCUIT_BREAKER}
      ExitOnCriticalError: ${EXIT_ON_CRITICAL_ERROR}
      Serilog__MinimumLevel: ${LOG_LEVEL}
    networks:
      - ams-project-backend
      - ams-project-infra
    restart: unless-stopped
    healthCheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/hc"]
      interval: 30s
      timeout: 10s
      retries: 3
      startPeriod: 40s


networks:
  ams-project-backend:
    external: true
  ams-project-infra:
    external: true
