# Reporting Context Fragment

metadata:
  name: Reporting
  description: Reporting (Scheduling Reporting) bounded context services

services:
  planning-reporting-migrator:
    image: amssolution/scheduling.reporting.migrator:linux-v3.1.0-pre
    containerName: planning-reporting-migrator
    lifecycle: init
    environment:
      ConnectionStrings__Reporting: ${AMS_DB}
      ConnectionStrings__ams: ${AMS_DB}
    networks:
      - ams-project-backend

  planning-reporting-api:
    image: amssolution/scheduling.reporting.api:linux-v3.1.0-pre
    containerName: planning-reporting-api
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ASPNETCORE_HTTP_PORTS: "8080"
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__ams: ${AMS_DB}
      Serilog__MinimumLevel: ${LOG_LEVEL}
    networks:
      - ams-project-backend
    restart: unless-stopped
    healthCheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/hc"]
      interval: 30s
      timeout: 10s
      retries: 3
      startPeriod: 40s

  planning-reporting-clienthub:
    image: amssolution/scheduling.reporting.clienthub:linux-v3.1.0-pre
    containerName: planning-reporting-clienthub
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ASPNETCORE_HTTP_PORTS: "8080"
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__ams: ${AMS_DB}
      ConnectionStrings__Transport: ${AMS_DB}
      ConnectionStrings__Persistence: ${AMS_DB}
      ServiceBusTimeToWaitBeforeTriggeringCircuitBreaker: ${SERVICE_BUS_TIME_TO_WAIT_BEFORE_TRIGGERING_CIRCUIT_BREAKER}
      ExitOnCriticalError: ${EXIT_ON_CRITICAL_ERROR}
      Serilog__MinimumLevel: ${LOG_LEVEL}
    networks:
      - ams-project-backend
      - ams-project-infra
    restart: unless-stopped
    healthCheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/hc"]
      interval: 30s
      timeout: 10s
      retries: 3
      startPeriod: 40s


networks:
  ams-project-backend:
    external: true
  ams-project-infra:
    external: true
