# IdentityAccess Stack Fragment
# IdentityServer-based identity provider services

metadata:
  name: IdentityAccess
  description: Identity Provider services (IdentityServer, AdminPortal, ClientHub, EmailSender)

variables:
  # IdentityAccess Database
  IDENTITY_ACCESS_DB:
    label: IdentityAccess Database Connection
    description: SQL Server connection string for IdentityAccess
    type: SqlServerConnectionString
    required: true
    group: Database


  # Email Settings
  MAIL_SERVER:
    label: Mail Server
    description: SMTP server hostname
    type: String
    required: true
    group: Email

  MAIL_PORT:
    label: Mail Port
    description: SMTP server port
    type: Port
    default: "587"
    group: Email

  MAIL_SENDER_NAME:
    label: Mail Sender Name
    description: Display name for outgoing emails
    type: String
    default: ams.project
    required: true
    group: Email

  MAIL_SENDER:
    label: Mail Sender Address
    description: Email address for outgoing emails
    type: Email
    required: true
    group: Email

  MAIL_PASSWORD:
    label: Mail Password
    description: SMTP authentication password
    type: Password
    group: Email

  MAIL_IS_AUTHENTICATION_REQUIRED:
    label: Mail Authentication Required
    description: Whether SMTP authentication is required
    type: Boolean
    default: "false"
    group: Email


  # Service Bus
  SERVICE_BUS_CATALOG:
    label: Service Bus Catalog
    description: SQL Server catalog for NServiceBus transport
    type: String
    required: true
    group: Advanced

  # Logging
  LOG_MAX_SIZE:
    label: Log Max Size
    description: Maximum size per log file
    type: String
    default: 5m
    group: Logging

  LOG_MAX_FILE:
    label: Log Max Files
    description: Maximum number of log files to retain
    type: String
    default: "3"
    group: Logging


services:
  identity-api:
    image: amssolution/identityaccess.identityserver:linux-latest
    containerName: identity-api
    ports:
      - "7614:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ConnectionStrings__IdentityAccess: ${IDENTITY_ACCESS_DB}
      ConnectionStrings__ams: ${AMS_DB}
      ServiceBusTimeToWaitBeforeTriggeringCircuitBreaker: ${SERVICE_BUS_TIME_TO_WAIT_BEFORE_TRIGGERING_CIRCUIT_BREAKER}
      ExitOnCriticalError: ${EXIT_ON_CRITICAL_ERROR}
      CultureCode: ${CULTURE_CODE}
      IdentityServerUrl: http://${AMS_PROJECT_EXTERNAL_DNS_NAME_OR_IP}:7614
      Serilog__LogstashUrl: http://${AMS_PROJECT_EXTERNAL_DNS_NAME_OR_IP}:8080
      Serilog__MinimumLevel: ${LOG_LEVEL}
      CertificatePath: /etc/ssl/certs/identity-api.pfx
      CertificatePassword: P@ssw0rd!
      SERVICE_BUS_CATALOG: ${SERVICE_BUS_CATALOG}
      ClientUrls__ProjectDesktop: http://localhost/wpf
      ClientUrls__ProjectDesktopV2: http://localhost/wpf
      ClientUrls__WebBffBaseUrls__0: http://${AMS_PROJECT_EXTERNAL_DNS_NAME_OR_IP}:5000
      ClientUrls__ReactClientBaseUrls__0: http://${AMS_PROJECT_EXTERNAL_DNS_NAME_OR_IP}:5000
    volumes:
      - profilePictures:/app/wwwroot/picture
    networks:
      - ams-project-identity
    restart: unless-stopped

  adminportal:
    image: amssolution/identityaccess.adminportal:linux-latest
    containerName: adminportal
    ports:
      - "7615:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ConnectionStrings__IdentityAccess: ${IDENTITY_ACCESS_DB}
      ConnectionStrings__ams: ${AMS_DB}
      ServiceBusTimeToWaitBeforeTriggeringCircuitBreaker: ${SERVICE_BUS_TIME_TO_WAIT_BEFORE_TRIGGERING_CIRCUIT_BREAKER}
      ExitOnCriticalError: ${EXIT_ON_CRITICAL_ERROR}
      CultureCode: ${CULTURE_CODE}
      IdentityServerUrl: http://identity-api
      Serilog__LogstashUrl: http://${AMS_PROJECT_EXTERNAL_DNS_NAME_OR_IP}:8080
      Serilog__MinimumLevel: ${LOG_LEVEL}
      SERVICE_BUS_CATALOG: ${SERVICE_BUS_CATALOG}
    networks:
      - ams-project-identity
    restart: unless-stopped

  identityaccess-clienthub:
    image: amssolution/identityaccess.clienthub:linux-latest
    containerName: identityaccess-clienthub
    ports:
      - "7616:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ConnectionStrings__IdentityAccess: ${IDENTITY_ACCESS_DB}
      ConnectionStrings__ams: ${AMS_DB}
      ServiceBusTimeToWaitBeforeTriggeringCircuitBreaker: ${SERVICE_BUS_TIME_TO_WAIT_BEFORE_TRIGGERING_CIRCUIT_BREAKER}
      ExitOnCriticalError: ${EXIT_ON_CRITICAL_ERROR}
      Serilog__LogstashUrl: http://${AMS_PROJECT_EXTERNAL_DNS_NAME_OR_IP}:8080
      Serilog__MinimumLevel: ${LOG_LEVEL}
      SERVICE_BUS_CATALOG: ${SERVICE_BUS_CATALOG}
    networks:
      - ams-project-identity
    restart: unless-stopped

  identityaccess-emailsender:
    image: amssolution/identityaccess.emailsender:linux-latest
    containerName: identityaccess-emailsender
    ports:
      - "7617:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ConnectionStrings__IdentityAccess: ${IDENTITY_ACCESS_DB}
      ConnectionStrings__ams: ${AMS_DB}
      ServiceBusTimeToWaitBeforeTriggeringCircuitBreaker: ${SERVICE_BUS_TIME_TO_WAIT_BEFORE_TRIGGERING_CIRCUIT_BREAKER}
      ExitOnCriticalError: ${EXIT_ON_CRITICAL_ERROR}
      CultureCode: ${CULTURE_CODE}
      EmailSettings__MailServer: ${MAIL_SERVER}
      EmailSettings__Port: ${MAIL_PORT}
      EmailSettings__SenderName: ${MAIL_SENDER_NAME}
      EmailSettings__Sender: ${MAIL_SENDER}
      EmailSettings__Password: ${MAIL_PASSWORD}
      EmailSettings__IsAuthenticationRequired: ${MAIL_IS_AUTHENTICATION_REQUIRED}
      Serilog__LogstashUrl: http://${AMS_PROJECT_EXTERNAL_DNS_NAME_OR_IP}:8080
      Serilog__MinimumLevel: ${LOG_LEVEL}
      SERVICE_BUS_CATALOG: ${SERVICE_BUS_CATALOG}
    networks:
      - ams-project-identity
    restart: unless-stopped

volumes:
  profilePictures: {}


networks:
  ams-project-identity:
    external: true
